name: Publish

on:
  release:
    types: [created]
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: PyPI
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build and Publish
        run: poetry publish --build
